### ISSUE TITLE
Problem undefined symbol in tf_sampling

### ISSUE THREAD

**Issue by IdeGelis** [xingyul/meteornet#10]
Hello,

Thank you for releasing your code and for your publication!

I am trying to train semantic_seg_synthia. The script stops just after launching 
`sh command_train_direct.sh` and give the following error:
![Capture d’écran de 2020-05-07 10-25-01](https://user-images.githubusercontent.com/25299213/81271949-122c5c00-904d-11ea-8491-93c1da83fcc7.png)

Do you have any idea about what is going on?

I compiled the Makefiles and obtained circular dependency problems for sampling and grouping operations. 

Thank you,

Looking forward to your reply.

**Comment by xingyul** [comment]
It seems like a problem with the compilation of TF Ops. What are your python and Tensorflow versions? The best is to follow the instruction in the README file.

**Comment by IdeGelis** [comment]
Hi,

I am using Pyhton 3.5 et Tensorflow-gpu 1.9.0 but the difference is that I am using Debian 9 and g++ 6.3.0.
But I finally succeed to compile TF Ops without circular dependency problems!! And thus manage to train the network with removing the following option in Makefiles : -D_GLIBCXX_USE_CXX11_ABI=0

Thank you for your attention,
Iris
