### ISSUE TITLE
Not able to compile "command_make.sh"

### ISSUE THREAD

**Issue by vajrag** [xingyul/meteornet#11]
hello,

I encountered a problem while compiling the file `command_make.sh`. I am getting the following error
> make: Circular tf_sampling_g.cu <- tf_sampling_g.cu.o dependency dropped.
> make: Nothing to be done for 'all'

I am using Tf-gpu = 1.9.0
Cuda version = 9.0
python 3.6

Can anyone suggest me how to solve this issue?

Thank you.

**Comment by xingyul** [comment]
If the `.so` file is produced, then it should be fine.
