### ISSUE TITLE
Unable to compile customized tf operators

### ISSUE THREAD

**Issue by munib94** [xingyul/meteornet#13]
When I try `sh command_make.sh` , I get the following error:
```
/usr/bin/ld: cannot find -ltensorflow_framework
collect2: error: ld returned 1 exit status
make: *** [Makefile:23: tf_interpolate_so.so] Error 1
```
I checked the path to `tf.sysconfig.get_lib()` and there is a file called "libtensorflow_framework.so.1". From [this post](https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary/42339395), I tried creating a symbolic link using `sudo ln -s /path/to/libtensorflow_framework.so.1 /path/to/libtensorflow_framework.so`. This got rid of the error, but the the compilation never finished and got stuck on this:
```
/usr/bin/ld: /home/user/.pyenv/versions/miniconda3-latest/envs/meteornet/lib/python3.5/site-packages/tensorflow/libtensorflow_framework.so: .dynsym local symbol at index 3 (>= sh_info of 3)
/usr/bin/ld: /home/user/.pyenv/versions/miniconda3-latest/envs/meteornet/lib/python3.5/site-packages/tensorflow/libtensorflow_framework.so: .dynsym local symbol at index 4 (>= sh_info of 3)
/usr/bin/ld: /home/user/.pyenv/versions/miniconda3-latest/envs/meteornet/lib/python3.5/site-packages/tensorflow/libtensorflow_framework.so: .dynsym local symbol at index 5 (>= sh_info of 3)
```
How do I resolve this?

Note: I modified the following lines for each makefile,
`CUDA_HOME := /usr/local/cuda-10.0`
`arch = sm_75`

**My system specs are:**
OS: Ubuntu 20.04
GPU: Titan RTX (Turing)
Tensorflow: tensorflow-gpu 1.14.0 (installed via pip)
Python: 3.5
CUDA: 10.0
cuDNN: 7.4.2

**Comment by xingyul** [comment]
Hi, the compilation is only tested in TF1.9.0. You can change the TF version to compile.
