### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Haiyan-Chris-Wang** [xingyul/meteornet#3]
when I run the sh command_train.sh, it keeps giving me the error of Segmentation fault (core dumped). Is it due to the problem of tf_ops?

**Comment by Haiyan-Chris-Wang** [comment]
![Selection_078](https://user-images.githubusercontent.com/31809601/72120974-9ed93e80-3327-11ea-8733-9ac8be0d925d.png)

**Comment by xingyul** [comment]
It's likely that you didn't set `arch` flag correctly in Makefiles.

**Comment by xingyul** [comment]
I'm so sorry, the TF version should be 1.9.0. That's my fault. I have updated the README in 2c7daff. I apologize for the trouble. Also thanks for bringing this up.

**Comment by Haiyan-Chris-Wang** [comment]
Thanks for solving the problem. The TF 1.9.0 works for me. However, for the MeteorNet-segmentation, how long did you take to train the model (150 epoches)? It seems very slow on my GTX 1080 Ti.






On Jan 11, 2020, at 1:49 AM, Xingyu Liu <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm so sorry, the TF version should be 1.9.0. That's my fault. I have updated the README in 2c7daff<https://github.com/xingyul/meteornet/commit/2c7daff8fdaa48b6c418a164d8ae84b40f343950>. I apologize for the trouble. Also thanks for bringing this up.
