### ISSUE TITLE
Segmentation fault (core dumped) for TF1.14

### ISSUE THREAD

**Issue by ihanwen99** [xingyul/meteornet#4]
My environment is same as this repo:
 - TF1.14.0 GPU
 - g++ 5.4.0
 - CUDA 9.0
 - Python 3.5
 on  Ubuntu 16.04.

Firstly, I face the problem of missing tensorflow_framework, I use 'get_link_flags()' to fetch tensorflow.framwork.so.1. While in the code, I could not use this so model with the error: segmentation fault.

So I think, should I down to TF1.13GPU for this code?

**Comment by diazandr3s** [comment]
The same happened to me. I solved it by using g++ 4.8

**Comment by ihanwen99** [comment]
> The same happened to me. I solved it by using g++ 4.8

Thank you very much, I will try again.

This environment problem confuse me for many hours.

**Comment by diazandr3s** [comment]
The same to me

**Comment by diazandr3s** [comment]
> > The same happened to me. I solved it by using g++ 4.8
> 
> Thank you very much, I will try again.
> 
> This environment problem confuse me for many hours.

Sorry, do you know exactly how to set arch? I'm using a Tesla K80. Should the arch be sm_37? How do you know which one to choose when compiling the TF ops?

**Comment by ihanwen99** [comment]
> > > The same happened to me. I solved it by using g++ 4.8
> > 
> > 
> > Thank you very much, I will try again.
> > This environment problem confuse me for many hours.
> 
> Sorry, do you know exactly how to set arch? I'm using a Tesla K80. Should the arch be sm_37? How do you know which one to choose when compiling the TF ops?

I haven't try yet, because my working environment is not available now. In my former try, I didn't change it, it still make *.so successfully.(I do not know whether it is truly correct)

My env uses 2080Ti. FYI.

**Comment by diazandr3s** [comment]
> > > > The same happened to me. I solved it by using g++ 4.8
> > > 
> > > 
> > > Thank you very much, I will try again.
> > > This environment problem confuse me for many hours.
> > 
> > 
> > Sorry, do you know exactly how to set arch? I'm using a Tesla K80. Should the arch be sm_37? How do you know which one to choose when compiling the TF ops?
> 
> I haven't try yet, because my working environment is not available now. In my former try, I didn't change it, it still make *.so successfully.(I do not know whether it is truly correct)
> 
> My env uses 2080Ti. FYI.

I did the same. I compiled them and got the *.so. But I am not sure why I'm getting this error when executing the train script for the **action_cls** application

tf_session.ExtendSession(self._session)tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op FarthestPoint ...

**Comment by ihanwen99** [comment]
> > > > > The same happened to me. I solved it by using g++ 4.8
> > > > 
> > > > 
> > > > Thank you very much, I will try again.
> > > > This environment problem confuse me for many hours.
> > > 
> > > 
> > > Sorry, do you know exactly how to set arch? I'm using a Tesla K80. Should the arch be sm_37? How do you know which one to choose when compiling the TF ops?
> > 
> > 
> > I haven't try yet, because my working environment is not available now. In my former try, I didn't change it, it still make *.so successfully.(I do not know whether it is truly correct)
> > My env uses 2080Ti. FYI.
> 
> I did the same. I compiled them and got the *.so. But I am not sure why I'm getting this error when executing the train script for the **action_cls** application
> 
> tf_session.ExtendSession(self._session)tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op FarthestPoint ...

Comfusing...

Later I will ask my senior, if I have any progress in this problem, I will let you know. ^_^

**Comment by xingyul** [comment]
I'm so sorry, the TF version should be 1.9.0. That's my fault. I have updated the README in 2c7daff8. I apologize for the trouble. Also thanks for bringing this up.
