### ISSUE TITLE
About Table3

### ISSUE THREAD

**Issue by Polar321124** [xingyul/meteornet#5]
Thanks for the work and the code, but I have a question:

In table 3, we see the IOU of category Bicyc is 0, So the accuracy of this category is also 0? 
But why the mAcc can catch 98.28? 

I tested the results of your code in pointnet++, I get follow results:
eval acc of Building:	 0.997244
eval acc of Road:	 0.986209
eval acc of Sidewalk:	 0.970941
eval acc of Fence:	 0.991735
eval acc of Vegetation:	 0.989693
eval acc of Pole:	 0.987906
eval acc of Car:	 0.963395
eval acc of Traffic Sign:	 0.910748
eval acc of Pedestrian:	 0.800363
eval acc of Bicycle:	 0.000000
eval acc of Lanemarking:	 0.866572
eval acc of Traffic Light:	 0.875165
eval accuracy: 0.861664

Did I make a mistake?

**Comment by xingyul** [comment]
Hi, thanks for the post. We actually made a mistake in the last column of Table 3. We reported overall accuracy instead of mean accuracy by mistake. We will correct the mistake in the updated version of the paper.
