### ISSUE TITLE
More Code to Release.

### ISSUE THREAD

**Issue by ihanwen99** [xingyul/meteornet#7]
May I request more code to release? I have been looking forward to it for a long time.

For example, KITTI, could you make your pre-processing code public, even if you do not release all the code. It is good opportunity for me to learn from your team. Your code is precise and beautiful.

**Comment by dsim174** [comment]
I am also waiting for KITTI Code!

**Comment by xingyul** [comment]
Hi, I have released the code for processing KITTI scene flow data. Please check commit 4573cf94bd3cca7e.
