### ISSUE TITLE
Flawed implementation of Meteor-rel module?

### ISSUE THREAD

**Issue by heiwang1997** [xingyul/meteornet#8]
When I am trying to run Meteor-rel module instead of the default Meteor-ind module, tensorflow complains about unmatched shapes. Looking into your implementation I think we need to change the following line:

https://github.com/xingyul/meteornet/blob/37a8a38df3cb2f3011a46e9191d580eee26723cd/utils/net_utils.py#L212

into

```
gathered_points = gather_point(points, sample_idx)
points_expand = tf.tile(tf.expand_dims(gathered_points, 2), [1,1,nsample,1])
```

Is that true? Or have I made any mistakes?

**Comment by xingyul** [comment]
Thanks a lot for catching this problem! It has been fixed in f5808c3656.
