### ISSUE TITLE
The action_cls experiment on processing depth map to point cloud

### ISSUE THREAD

**Issue by liujiaheng** [xingyul/meteornet#9]
![image](https://user-images.githubusercontent.com/27964642/81051790-f615a700-8ef4-11ea-8bed-a3f79f91cc7f.png)

I see the value of focal is 280. I cannot find where to get the focal value of the MSRAction3d dataset.
Specifically, I want to use NTU-RGBd dataset to do the classification problem.
So I want to know how to process the depth map sequences of NTU-RGBd dataset to point cloud sequences.

Thanks,
Looking forward to your reply.

**Comment by xingyul** [comment]
Hi, MSRAction3D dataset didn't provide focal length. So we just picked a focal length value that gives reasonable 3D reconstructions. This value doesn't affect too much in the final results.
